/* Generated By:JJTree: Do not edit this line. ASTAnonymousFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.liyaos.simpl.parser;

public
class ASTAnonymousFunction extends SimpleNode {
  public ASTAnonymousFunction(int id) {
    super(id);
  }

  public ASTAnonymousFunction(SimPLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimPLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=991a65142ba818421e1a8c4c2785be53 (do not edit this line) */
