/* Generated By:JJTree: Do not edit this line. ASTAnonymousFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.liyaos.simpl.parser;
import com.liyaos.simpl.types.Types;

public
class ASTAnonymousFunction extends SimPLNode {



  private Types paramType;
  private Types returnType;

  public Types getReturnType() {
    return returnType;
  }

  public void setReturnType(Types returnType) {
    this.returnType = returnType;
  }

  public Types getParamType() {
    return paramType;
  }

  public void setParamType(Types paramType) {
    this.paramType = paramType;
  }

  public ASTAnonymousFunction(int id) {
    super(id);
  }

  public ASTAnonymousFunction(SimPLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimPLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ae2fc1a61c3fa3876767efbb523f5b2b (do not edit this line) */
