/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.liyaos.simpl.parser;

public
class ASTIdentifier extends SimPLNode {

  private String value;

  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(SimPLParser p, int id) {
    super(p, id);
  }

  public void setValue(String img) {
    value = img;
  }

  public String getValue() {
    return value;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(SimPLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bd676763da3ac199c621afcae74527ad (do not edit this line) */
