/* Generated By:JJTree&JavaCC: Do not edit this line. SimPLConstants.java */
package com.liyaos.simpl.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimPLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LET = 5;
  /** RegularExpression Id. */
  int IN = 6;
  /** RegularExpression Id. */
  int END = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int THEN = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int DO = 12;
  /** RegularExpression Id. */
  int FST = 13;
  /** RegularExpression Id. */
  int SND = 14;
  /** RegularExpression Id. */
  int HEAD = 15;
  /** RegularExpression Id. */
  int TAIL = 16;
  /** RegularExpression Id. */
  int FUN = 17;
  /** RegularExpression Id. */
  int NIL = 18;
  /** RegularExpression Id. */
  int CONS = 19;
  /** RegularExpression Id. */
  int OPAR = 20;
  /** RegularExpression Id. */
  int CPAR = 21;
  /** RegularExpression Id. */
  int COMMA = 22;
  /** RegularExpression Id. */
  int ASSIGN = 23;
  /** RegularExpression Id. */
  int SEMICOLON = 24;
  /** RegularExpression Id. */
  int DEFUN = 25;
  /** RegularExpression Id. */
  int INT = 26;
  /** RegularExpression Id. */
  int BOOL = 27;
  /** RegularExpression Id. */
  int PLUS = 28;
  /** RegularExpression Id. */
  int MINUS = 29;
  /** RegularExpression Id. */
  int TIMES = 30;
  /** RegularExpression Id. */
  int DIVIDE = 31;
  /** RegularExpression Id. */
  int EQ = 32;
  /** RegularExpression Id. */
  int GREATERTHAN = 33;
  /** RegularExpression Id. */
  int LESSTHAN = 34;
  /** RegularExpression Id. */
  int AND = 35;
  /** RegularExpression Id. */
  int OR = 36;
  /** RegularExpression Id. */
  int UMINUS = 37;
  /** RegularExpression Id. */
  int NOT = 38;
  /** RegularExpression Id. */
  int IDENTIFIER = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"let\"",
    "\"in\"",
    "\"end\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"fst\"",
    "\"snd\"",
    "\"head\"",
    "\"tail\"",
    "\"fun\"",
    "\"nil\"",
    "\"::\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\":=\"",
    "\";\"",
    "\"->\"",
    "<INT>",
    "<BOOL>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"and\"",
    "\"or\"",
    "\"~\"",
    "\"not\"",
    "<IDENTIFIER>",
  };

}
