/* Generated By:JavaCC: Do not edit this line. SimPLVisitor.java Version 5.0 */
package com.liyaos.simpl.parser;

public interface SimPLVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTLet node, Object data);
  public Object visit(ASTIf node, Object data);
  public Object visit(ASTWhile node, Object data);
  public Object visit(ASTSequence node, Object data);
  public Object visit(ASTAnonymousFunction node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTCons node, Object data);
  public Object visit(ASTAndOr node, Object data);
  public Object visit(ASTCompare node, Object data);
  public Object visit(ASTPlusMinus node, Object data);
  public Object visit(ASTTimesDivide node, Object data);
  public Object visit(ASTNegetive node, Object data);
  public Object visit(ASTNot node, Object data);
  public Object visit(ASTBool node, Object data);
  public Object visit(ASTInt node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTFst node, Object data);
  public Object visit(ASTSnd node, Object data);
  public Object visit(ASTHead node, Object data);
  public Object visit(ASTTail node, Object data);
  public Object visit(ASTApplication node, Object data);
  public Object visit(ASTPair node, Object data);
  public Object visit(ASTBracket node, Object data);
}
/* JavaCC - OriginalChecksum=cfc64a3a103170346f2e53011a94bffa (do not edit this line) */
