/* Generated By:JavaCC: Do not edit this line. SimPLTreeConstants.java Version 5.0 */
package com.liyaos.simpl.parser;

public interface SimPLTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTLET = 2;
  public int JJTIF = 3;
  public int JJTWHILE = 4;
  public int JJTSEQUENCE = 5;
  public int JJTANONYMOUSFUNCTION = 6;
  public int JJTASSIGNMENT = 7;
  public int JJTCONS = 8;
  public int JJTANDOR = 9;
  public int JJTCOMPARE = 10;
  public int JJTPLUSMINUS = 11;
  public int JJTTIMESDIVIDE = 12;
  public int JJTNEGETIVE = 13;
  public int JJTNOT = 14;
  public int JJTBOOL = 15;
  public int JJTINT = 16;
  public int JJTIDENTIFIER = 17;
  public int JJTFST = 18;
  public int JJTSND = 19;
  public int JJTHEAD = 20;
  public int JJTTAIL = 21;
  public int JJTAPPLICATION = 22;
  public int JJTPAIR = 23;
  public int JJTBRACKET = 24;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Let",
    "If",
    "While",
    "Sequence",
    "AnonymousFunction",
    "Assignment",
    "Cons",
    "AndOr",
    "Compare",
    "PlusMinus",
    "TimesDivide",
    "Negetive",
    "Not",
    "Bool",
    "Int",
    "Identifier",
    "Fst",
    "Snd",
    "Head",
    "Tail",
    "Application",
    "Pair",
    "Bracket",
  };
}
/* JavaCC - OriginalChecksum=77506b8ddf989549e30100ffb98a7536 (do not edit this line) */
