/* Generated By:JavaCC: Do not edit this line. SimPLParserVisitor.java Version 5.0 */
package com.liyaos.simpl.parser;

import com.liyaos.simpl.types.TypeErrorException;

public interface SimPLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTLet node, Object data);
  public Object visit(ASTIf node, Object data);
  public Object visit(ASTWhile node, Object data);
  public Object visit(ASTSequence node, Object data);
  public Object visit(ASTAnonymousFunction node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTCons node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTEq node, Object data);
  public Object visit(ASTGreaterThan node, Object data);
  public Object visit(ASTLessThan node, Object data);
  public Object visit(ASTPlus node, Object data);
  public Object visit(ASTMinus node, Object data);
  public Object visit(ASTTimes node, Object data);
  public Object visit(ASTDivide node, Object data);
  public Object visit(ASTNegative node, Object data);
  public Object visit(ASTNot node, Object data);
  public Object visit(ASTBool node, Object data);
  public Object visit(ASTInt node, Object data);
  public Object visit(ASTNil node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTFst node, Object data);
  public Object visit(ASTSnd node, Object data);
  public Object visit(ASTHead node, Object data);
  public Object visit(ASTTail node, Object data);
  public Object visit(ASTApplication node, Object data);
  public Object visit(ASTPair node, Object data);
  public Object visit(ASTBracket node, Object data);
}
/* JavaCC - OriginalChecksum=49bafcaaa3b97cb267eeaca761ec875c (do not edit this line) */
