/* Generated By:JavaCC: Do not edit this line. SimPLParserTreeConstants.java Version 5.0 */
package com.liyaos.simpl.parser;

public interface SimPLParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTLET = 2;
  public int JJTIF = 3;
  public int JJTWHILE = 4;
  public int JJTSEQUENCE = 5;
  public int JJTANONYMOUSFUNCTION = 6;
  public int JJTASSIGNMENT = 7;
  public int JJTCONS = 8;
  public int JJTAND = 9;
  public int JJTOR = 10;
  public int JJTEQ = 11;
  public int JJTGREATERTHAN = 12;
  public int JJTLESSTHAN = 13;
  public int JJTPLUS = 14;
  public int JJTMINUS = 15;
  public int JJTTIMES = 16;
  public int JJTDIVIDE = 17;
  public int JJTNEGATIVE = 18;
  public int JJTNOT = 19;
  public int JJTBOOL = 20;
  public int JJTINT = 21;
  public int JJTIDENTIFIER = 22;
  public int JJTFST = 23;
  public int JJTSND = 24;
  public int JJTHEAD = 25;
  public int JJTTAIL = 26;
  public int JJTAPPLICATION = 27;
  public int JJTPAIR = 28;
  public int JJTBRACKET = 29;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "Let",
    "If",
    "While",
    "Sequence",
    "AnonymousFunction",
    "Assignment",
    "Cons",
    "And",
    "Or",
    "Eq",
    "GreaterThan",
    "LessThan",
    "Plus",
    "Minus",
    "Times",
    "Divide",
    "Negative",
    "Not",
    "Bool",
    "Int",
    "Identifier",
    "Fst",
    "Snd",
    "Head",
    "Tail",
    "Application",
    "Pair",
    "Bracket",
  };
}
/* JavaCC - OriginalChecksum=cdcbf806f1f98f338b21bd1d6c5cdad8 (do not edit this line) */
